name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Install openscad
      run: sudo apt install openscad
    - name: Export stl with openscad
      run: openscad -o compact-z-probe.stl compact-z-probe.scad
