name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install openscad
      run: apt install openscad
    - name: Export stl with openscad
      run: openscad --info -o compact-z-probe.stl compact-z-probe.stl
